executable   = /home/kyang/master_grid/ml/weights/condor_submit/add_weights_$(ProcId).sh
output       = /home/kyang/master_grid/ml/weights/condor_submit/out_$(ProcId).txt
error        = /home/kyang/master_grid/ml/weights/condor_submit/error_$(ProcId).txt
log          = /home/kyang/master_grid/ml/weights/condor_submit/add_weights_$(ProcId).log
max_retries  = 3
requirements = Machine =!= LastRemoteHost

should_transfer_files=YES
request_memory = 2000M
queue 122
