import datetime
import plot
import copy

cfg_1 = {"start_date" :"2023_12_01",
         "end_date" : "2023_12_31",
         "variables" : ["modificationtime","jobstatus"],
         "title" : "",
         "hist_name" : "modtime",
         "bins" :31,
         "ylabel" : "Probability",
         "xlabel": "IO Intensity",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "modificationtime",
         "y" : None,
         "x_rotate" : 30,
         "datetime_var" : ["modificationtime"],
         "condition" :"(((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"stack",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}


cfg_4 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","io_intensity"],
         "title" : "",
         "hist_name" : "io_intensity",
         "bins" :50,
         "ylabel" : "Probability",
         "xlabel": "IO Intensity",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "io_intensity",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['io_intensity'] < 2e6) & (data['io_intensity'] > 0) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_5 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","wall_time"],
         "title" : "",
         "hist_name" : "wall_time",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "Walltime",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "wall_time",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['wall_time'] < 30000) & (data['wall_time'] > 0) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_6 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","diskio"],
         "title" : "",
         "hist_name" : "diskio",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "Disk IO",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "diskio",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['diskio'] < 10000) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_7 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","memory_leak"],
         "title" : "",
         "hist_name" : "memory_leak",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "Memory Leak",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "memory_leak",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['memory_leak'] < 5000) & (data['memory_leak'] > -2500) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_8 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","IObytesWriteRate"],
         "title" : "",
         "hist_name" : "IObytesWriteRate",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "IO Bytes Write Rate",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "IObytesWriteRate",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['IObytesWriteRate'] < 3.5e8) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_9 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","IObytesReadRate"],
         "title" : "",
         "hist_name" : "IObytesReadRate",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "IO Bytes Read Rate",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "IObytesReadRate",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['IObytesReadRate'] < 2e8) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_10 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","IObytesRead"],
         "title" : "",
         "hist_name" : "IObytesRead",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "IO Bytes Read",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "IObytesRead",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
          "condition" :"((data['IObytesRead'] < 0.6e7) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_11 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","IObytesWritten"],
         "title" : "",
         "hist_name" : "IObytesWritten",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "IO Bytes Written",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "IObytesWritten",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
          "condition" :"((data['IObytesWritten'] < 1.3e7) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_12 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","outputfilebytes"],
         "title" : "",
         "hist_name" : "outputfilebytes",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "Output File Bytes",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "outputfilebytes",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
          "condition" :"((data['outputfilebytes'] < 1e9) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_13 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","actualcorecount"],
         "title" : "",
         "hist_name" : "actualcorecount",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "Core Count",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "actualcorecount",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['actualcorecount'] < 100) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_14 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","inputfilebytes"],
         "title" : "",
         "hist_name" : "inputfilebytes",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "Input File Bytes",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "inputfilebytes",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
          "condition" :"((data['inputfilebytes'] < 4e10) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_15 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","cpu_eff"],
         "title" : "",
         "hist_name" : "cpu_eff",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "CPU Efficiency",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "cpu_eff",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['cpu_eff'] < 1.25) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

cfg_16 = {"start_date" :"2023_08_01",
         "end_date" : "2023_10_31",
         "variables" : ["modificationtime","jobstatus","cpuconsumptiontime"],
         "title" : "",
         "hist_name" : "cpuconsumptiontime",
         "bins" :100,
         "ylabel" : "Probability",
         "xlabel": "CPU Consumption Time",
         "xticks" : [],
         "normalize": True,
         "hue" : "jobstatus",
         "fig_size" : (10,5),
         "x" : "cpuconsumptiontime",
         "y" : None,
         "x_rotate" : 0,
         "datetime_var" : ["modificationtime"],
         "condition" :"((data['cpuconsumptiontime'] < 15000) & ((data['jobstatus'] == 'finished') | (data['jobstatus'] == 'failed')))",
         "type":"step",
         "y_log_scale" : False,
         "x_log_scale" : False,
         "class_color": {"failed":"red","finished":"green"},
         "hue_order":["finished","failed"],
}

#cfgs = [cfg_4,cfg_5,cfg_6,cfg_7,cfg_8,cfg_9,cfg_10,cfg_11,cfg_12,cfg_13,cfg_14,cfg_15,cfg_16,]
cfgs=[cfg_18]
histo_plotting = plot.hist_plot(cfgs)
histo_plotting.create_plots()
