executable   = /home/kyang/master_grid/plotting/plot.sh
output       = /home/kyang/master_grid/plotting/out_$(ProcId).txt
error        = /home/kyang/master_grid/plotting/error_$(ProcId).txt
log          = /home/kyang/master_grid/plotting/plot_$(ProcId).log
max_retries  = 5
requirements = Machine =!= LastRemoteHost

should_transfer_files=YES
request_memory = 5GB
request_disk = 1GB
request_cpus = 6
queue 1

