executable   = /home/kyang/master_grid/ml/model/run_training.sh
output       = /home/kyang/master_grid/ml/model/model/out_$(ProcId).txt
error        = /home/kyang/master_grid/ml/model/model/error_$(ProcId).txt
log          = /home/kyang/master_grid/ml/model/model/run_training_$(ProcId).log
max_retries  = 3
requirements = Machine =!= LastRemoteHost

should_transfer_files=YES
request_memory = 50GB
request_cpus = 8
rank = 8
queue 1
