executable   = /home/kyang/master_grid/ml/model/inject/condor_submit/inject_$(ProcID).sh
output       = /home/kyang/master_grid/ml/model/inject/condor_submit/out_$(ProcId).txt
error        = /home/kyang/master_grid/ml/model/inject/condor_submit/error_$(ProcId).txt
log          = /home/kyang/master_grid/ml/model/inject/condor_submit/inject_$(ProcId).log
max_retries  = 5
requirements = Machine =!= LastRemoteHost

should_transfer_files=YES
request_memory = 2GB
request_disk = 1GB
request_cpus = 4
rank = 4
queue 61
