executable   = /home/kyang/master_grid/skim/condor_skim/skim_$(ProcId).sh
output       = /home/kyang/master_grid/skim/condor_skim/out_$(ProcId).txt
error        = /home/kyang/master_grid/skim/condor_skim/error_$(ProcId).txt
log          = /home/kyang/master_grid/skim/condor_skim/skim_$(ProcId).log
max_retries  = 3
requirements = Machine =!= LastRemoteHost

use_x509userproxy=True
x509userproxy = $ENV(X509_USER_PROXY)

should_transfer_files=YES
request_memory = 3000M
queue 2
