executable   = /home/kyang/master_grid/ml/model/preprocessing/condor_submit/preprocess_$(ProcID).sh
output       = /home/kyang/master_grid/ml/model/preprocessing/condor_submit/out_$(ProcId).txt
error        = /home/kyang/master_grid/ml/model/preprocessing/condor_submit/error_$(ProcId).txt
log          = /home/kyang/master_grid/ml/model/preprocessing/condor_submit/preprocess_$(ProcId).log
max_retries  = 5
requirements = Machine =!= LastRemoteHost

should_transfer_files=YES
request_memory = 2GB
request_disk = 1GB
queue 153
